### ISSUE TITLE
Cannot compile ZOS on ubuntu linux

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/zosctl#10]
weynand@Ubimac:~/opt/GitHub/zos$  nimble static
       Info Hint: used config file '/etc/nim.cfg' [Conf]
     Error: Could not read package info file in /home/weynand/opt/GitHub/zos/zos.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     home/weynand/opt/GitHub/zos/zos.nimble(19, 1) Error: wrong number of arguments.
weynand@Ubimac:~/opt/GitHub/zos$ vi zos.nimble
weynand@Ubimac:~/opt/GitHub/zos$ uname -a
Linux Ubimac 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
weynand@Ubimac:~/opt/GitHub/zos$ 

Nim version:
weynand@Ubimac:~/opt/GitHub/zos$ nim -h
Nim Compiler Version 0.17.2 (2018-02-05) [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf
::

    nim command [options] [projectfile] [arguments]

Command:
  compile, c                compile project with default code generator (C)
  doc                       generate the documentation for inputfile
  doc2                      generate the documentation for inputfile

**Comment by weynandkuijpers** [comment]
And when compiling:
weynand@Ubimac:~/opt/GitHub/zos$  nimble static
       Info Hint: used config file '/etc/nim.cfg' [Conf]
     Error: Could not read package info file in /home/weynand/opt/GitHub/zos/zos.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     home/weynand/opt/GitHub/zos/zos.nimble(19, 1) Error: wrong number of arguments.

I guess this is solved - the stadard Ubuntu nim lang package is an older version - when you download the latest tarball - it compiles without the error in the zos.nimple file - however the compile fails (see next comment)

**Comment by weynandkuijpers** [comment]
Downloaded the latest version of nimble and compiled it:

weynand@Ubimac:~/opt/GitHub/zos$ nimble -v
nimble v0.9.0 compiled at 2018-10-11 09:26:08
git hash: couldn't determine git hash

Compile error like this
eynand@Ubimac:~/opt/GitHub/zos$ which nimble
/home/weynand/.nimble/bin/nimble
weynand@Ubimac:~/opt/GitHub/zos$ nimble zosbuild
  Executing task zosbuild in /home/weynand/opt/GitHub/zos/zos.nimble
  Verifying dependencies for zos@0.1.0
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
 Installing docopt@any version
Downloading https://github.com/docopt/docopt.nim using git
  Verifying dependencies for docopt@0.6.6
 Installing docopt@0.6.6
   Success: docopt installed successfully.
 Installing redisclient@any version
Downloading https://github.com/xmonader/nim-redisclient using git
  Verifying dependencies for redisclient@0.1.0
 Installing redisparser@>= 0.1.0
Downloading https://github.com/xmonader/nim-redisparser using git
  Verifying dependencies for redisparser@0.1.0
 Installing redisparser@0.1.0
   Success: redisparser installed successfully.
 Installing redisclient@0.1.0
   Success: redisclient installed successfully.
 Installing uuids@any version
Downloading https://github.com/pragmagic/uuids using git
  Verifying dependencies for uuids@0.1.10
 Installing isaac@>= 0.1.3
Downloading https://github.com/pragmagic/isaac using git
  Verifying dependencies for isaac@0.1.3
 Installing isaac@0.1.3
   Success: isaac installed successfully.
 Installing uuids@0.1.10
   Success: uuids installed successfully.
   Building zos/zos using c backend
       Tip: 46 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1064)         doAction
        ... nimble.nim(510)          build
        ... nimble.nim(245)          buildFromDir
        ... Build failed for package: zos
        ... Details:
        ... nimble.nim(1106)         nimble
        ... nimble.nim(1064)         doAction
        ... nimble.nim(510)          build
        ... nimble.nim(237)          buildFromDir
        ... tools.nim(37)            doCmd
        ... Execution failed with exit code 1
        ... Command: "/home/weynand/.nimble/bin/nim" c --noBabelPath -d:ssl --path:"/tmp/nimble_3204/githubcom_docoptdocoptnim/src"  --path:"/tmp/nimble_3204/githubcom_xmonadernimredisparser_0.1.0/src"  --path:"/tmp/nimble_3204/githubcom_xmonadernimredisclient/src"  --path:"/tmp/nimble_3204/githubcom_pragmagicisaac_0.1.3/src"  --path:"/tmp/nimble_3204/githubcom_pragmagicuuids"  -o:"/home/weynand/opt/GitHub/zos/zos" "/home/weynand/opt/GitHub/zos/src/zos.nim"
        ... Output: Hint: used config file '/home/weynand/.choosenim/toolchains/nim-0.19.0/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: zos [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: os [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: linux [Processing]
        ... Hint: tables [Processing]
        ... Hint: uri [Processing]
        ... Hint: parsecfg [Processing]
        ... Hint: lexbase [Processing]
        ... Hint: json [Processing]
        ... Hint: parsejson [Processing]
        ... Hint: marshal [Processing]
        ... Hint: typeinfo [Processing]
        ... Hint: intsets [Processing]
        ... Hint: net [Processing]
        ... Hint: nativesockets [Processing]
        ... Hint: sets [Processing]
        ... Hint: openssl [Processing]
        ... Hint: dynlib [Processing]
        ... Hint: asyncdispatch [Processing]
        ... Hint: heapqueue [Processing]
        ... Hint: lists [Processing]
        ... Hint: asyncstreams [Processing]
        ... Hint: asyncfutures [Processing]
        ... Hint: deques [Processing]
        ... Hint: cstrutils [Processing]
        ... Hint: selectors [Processing]
        ... Hint: epoll [Processing]
        ... Hint: asyncnet [Processing]
        ... Hint: redisclient [Processing]
        ... Hint: redisparser [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: docopt [Processing]
        ... Hint: nre [Processing]
        ... Hint: pcre [Processing]
        ... Hint: util [Processing]
        ... Hint: util [Processing]
        ... ../../../../../../tmp/nimble_3204/githubcom_docoptdocoptnim/src/docopt/util.nim(36, 16) template/generic instantiation from here
        ... ../../../../.choosenim/toolchains/nim-0.19.0/lib/system.nim(414, 10) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
stack trace: (most recent call last)
/home/weynand/opt/GitHub/zos/zos.nimble(17) zosbuildTask
/home/weynand/.choosenim/toolchains/nim-0.19.0/lib/system/nimscript.nim(237) exec
/home/weynand/.choosenim/toolchains/nim-0.19.0/lib/system/nimscript.nim(237, 7) Error: unhandled exception: FAILED: nimble build -d:ssl

**Comment by xmonader** [comment]
Should be fixed by latest
