### ISSUE TITLE
rename/archive repository

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/zosctl#102]
I'm opening this issue to see if we could rename/archive this repository so his name can be re-used for another repository.

The 0-OS v2 is nearly ready to have it's first release published and we would like to use the canonical name `zos` for out repository. It is currently called [zosv2](https://github.com/threefoldtech/zosv2/) but we don't want to have a strange version number in our repository name.

Since this repository is going to be obsolete as the v2 is release I would like to rename then archive it.

See detail about the why: https://github.com/threefoldtech/zosv2/issues/240

**Comment by xmonader** [comment]
No problem, renamed it to zosctl for now not sure if there're any plans for it right now.

**Comment by delandtj** [comment]
thankz alot
well zosctl can only work against zosv1
zos doensn't have an API any more ...

**Comment by zaibon** [comment]
@xmonader thanks a lot :-)
