### ISSUE TITLE
zos init needs to be more errorprone

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/zosctl#11]
![image](https://user-images.githubusercontent.com/6021844/46804433-d8a54900-cd62-11e8-9aa1-f80b37d4d52e.png)

**Comment by despiegk** [comment]
check if dir exists, ...
ask to remove

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/zos/commit/ba6fe68dbc4e629b5f4ae68d6e68d0a6941406eb

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
23d648312221ff8e4d0d938e22d7d5aacd19b70e

# Verification Steps:
-- we need to check if we remove the zos node, it's directory will be removed from ```VirtualBox VMs``` directory.  
- ll /root/VirtualBox\ VMs 
```total 12K
drwx------ 3 root root 4.0K Oct 18 08:25 create
drwx------ 3 root root 4.0K Oct 22 12:36 new
drwx------ 2 root root 4.0K Oct 22 18:05 new2
```

- zos remove --name="create"
```
INFO deleted vm create
```

- ll /root/VirtualBox\ VMs    
```total 8.0K
drwx------ 3 root root 4.0K Oct 22 12:36 new
drwx------ 2 root root 4.0K Oct 22 18:05 new2
```
