### ISSUE TITLE
container  exec has terrible output, needs to be as close as possible how it would be in the shell itself

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/zosctl#17]
![image](https://user-images.githubusercontent.com/6021844/46807048-62f0ab80-cd69-11e8-94ec-a4a5a545d68b.png)

**Comment by despiegk** [comment]
like ssh would do it

**Comment by despiegk** [comment]
why not use ssh to execute it?

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
9956345c45e6a0a3fa17fd431eeddbe9fa77b224

# Verification Steps:
- ./zos container new --name=jumpscale --root="https://hub.grid.tf/tf-official-apps/ubuntu-bionic-build.flist"
- ./zos container exec "curl https://raw.githubusercontent.com/threefoldtech/jumpscale_core/development_simple/install.sh?$RANDOM > /tmp/install_jumpscale.sh;bash /tmp/install_jumpscale.sh"

![output](https://user-images.githubusercontent.com/21218053/47081236-5907f600-d20a-11e8-8734-fe782503acdc.png)
