### ISSUE TITLE
ssh behaviour on zos init

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/zosctl#19]
- check ssh-agent is loaded & has 1 key, if yes use that one
- check there is ~/.ssh/... if yes use that one
- if no key, ask user if we should generate one for them, if yes do the generation

**Comment by xmonader** [comment]
ssh behavior is container only now

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
1e3f6560ebb9f6b566f603cf76b251c10a67e959

# Verification steps:
- create one container with ssh-agent is loaded and have only one key. 
- I killed ssh-agent and try to create a new container, it loaded using the key stored in ~/.ssh/... 
- I killed ssh-agent and remove ssh key file from default paths and try to create new container and i got this message 

```
dispatch creating test-agent-3 on machine https://hub.grid.tf/tf-official-apps/ubuntu-bionic-build.flist false
ERROR couldn't find sshkeys in agent or in default paths [generate one with ssh-keygen]
```
