### ISSUE TITLE
ssh extension to zos

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/zosctl#22]
## use SSH where possible

- set of commands which use SSH interaction with container
- each command below should use SSH if SSH was ever enabled on a container

### execute command in container 

use ssh to execute the command, this will make sure to execute using SSH command or through the wrapper ZOS is the same

```
zos container $id exec 'ls /'
```

### execute ssh session to container

```
zos container $id shell
```

### copy file/dir

use rsync over ssh

```
zos container $id upload /mylocal/dir /tmp/remote
zos container $id download /mylocal/dir /tmp/remote

```

### generic

$id is optional, can be left away then will be last one !!!

**Comment by xmonader** [comment]
done on the development branch

*scp used for upload/download (rsync to be in both sides) (creating ssh/rsync flist now)

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
23d648312221ff8e4d0d938e22d7d5aacd19b70e

# Verification Steps:

- zos container shell
- zos container 128 shell
- zos container exec 'ls /'
- zos container 128 exec 'ls /'
- zos container upload /root/test-upload /tmp/
- zos container 128 upload /root/test-upload /tmp/
- zos container  download /tmp/test-upload/ /root/test/
- zos container 128  download /root/test-upload/ /root/test/
