### ISSUE TITLE
i removed the vm, and I wanted to restart

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/zosctl#24]
![image](https://user-images.githubusercontent.com/6021844/46809485-dc3ecd00-cd6e-11e8-88c6-cf710002d988.png)

nat rules where not removed

needs to be checked & removed when possible

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/zos/commit/ba6fe68dbc4e629b5f4ae68d6e68d0a6941406eb

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
23d648312221ff8e4d0d938e22d7d5aacd19b70e

# Verification Steps:

> When we create a zos node , it create a nat rule for redis port. Here, we need to make sure that a nat rule is removed after we remove the zos node. so after we create a zos node using certain port, we will remove it and try to create another vm with different name using same port. 

- zos init --name="test1" --redisport=9999

```
** executing command vboxmanage modifyvm test1   --memory=4096
** executing command vboxmanage modifyvm test1   --ioapic on
** executing command vboxmanage modifyvm test1   --boot1 dvd --boot2 disk
** executing command vboxmanage modifyvm test1   --nic1 nat
** executing command vboxmanage modifyvm test1   --vrde on 
** executing command vboxmanage modifyvm test1   --natpf1 "redis,tcp,,9999,,6379" 
INFO created machine test1
INFO preparing zos machine...may take a while..
PONG
INFO created zos machine and we are ready.
```

- zos remove --name="test1"

- zos init --name="test2" --redisport=9999

```
ERROR port 9999 already taken by test1
```
