### ISSUE TITLE
ZOS runtime error after compilation on macos

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/zosctl#27]
Issue:
After installing brew and the nim package on a virgin Macos system - successful compilation results in app error.  The app error is there because the .config directory does not exist on standard Macos.  Creating the .config directory resolves the issue (mkdir ~/.config). the zos.toml file does not have to exist, this one is created.

Suggestion:
Maybe add a check for the existence of the ~/.config directory - if not create it.

**Comment by xmonader** [comment]
Thank you I solved that on development branch https://github.com/threefoldtech/zos/blob/development/src/zos.nim#L21

will merge all the updates in master on sunday

Note: development currently under lots of refactoring and might be broken, but you can give it  a try :)
