### ISSUE TITLE
Command without any input parameters provides misleading error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/zosctl#28]
weynand@Ubimac:~/.config$ zos
Unsupported command

I guess showing same as ''zos -help'' is a better option.

**Comment by xmonader** [comment]
Thanks! Fixed on development
https://github.com/threefoldtech/zos/commit/0b235c39fc94a3582be59cfc021e8b4d4cb3834e

**Comment by Dina-Abd-Elrahman** [comment]
# Zos Version:
b84f527a31867727e00ba0abb8ca150d12892787

# Verification Step:
```
- nimble zos
- ./zos
```
