### ISSUE TITLE
allow mounting directories from reachable containers

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#32]
using sshfs allow

`./zos mount <id> /opt/code/machine1`

will mount the current active container or container with container id <id> into /opt/code/machine1 directory using sshfs

**Comment by xmonader** [comment]
6f0ee7f2132fd77204c7dc93ba9f809b21f9d086 
docs  7cd9e787d8f953b1f9cd6c4fed116113845c5e1a

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
2a97f62d3b236c2f741caa82592fc1ab893e7156

# Verification Steps:
- mkdir /tmp/dinamount
- ./zos container mount / /tmp/dinamount
- echo "test mount" /tmp/dinamount/testtttt

on container side:
- cat /testtttt

```
test mount
```
