### ISSUE TITLE
issue with creating zos node with same name, different port. 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/zosctl#41]
- when trying to create new zos node with name of zos nodes exists before , but different redis port . without --reset option it starting the old node is started normally with old port ( without warning message )

**Comment by xmonader** [comment]
Fixed here https://github.com/threefoldtech/zos/commit/ba6fe68dbc4e629b5f4ae68d6e68d0a6941406eb and added description of the correct behavior

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
619b56a321c99b7c7ce333b2143dc0250b9514d1

# Verification steps:
- ./zos init --name="new2" --redisport=7779
```WARN Invalid port value: {parsed} will use default for now.
WARN new2 is already configured against 6379 and you want it to use 7779
continue? [Y/n]: 
y
** executing command vboxmanage modifyvm new2   --memory=4096
```
