### ISSUE TITLE
after switching to new ZOS node, new created continers created on old ZOS node

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/zosctl#47]
# ZOS Version:
619b56a321c99b7c7ce333b2143dc0250b9514d1

# Verification steps:
-  ./zos container shell
```INFO sshing to container 342 on dina```

- note: 
342 is the number of last container in old ZOS node

**Comment by xmonader** [comment]
Did it successfully switch? what is the output of 
`./zos showconfig | grep defaultzos`
