### ISSUE TITLE
need to fix upload for directory

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/zosctl#48]
- we cannot upload directory to container.

# ZOS Version:
619b56a321c99b7c7ce333b2143dc0250b9514d1

# Verification Steps:
- ./zos container 10 upload /root/test-upload /tmp/ 
```ERROR file /root/test-upload doesn't exist```

**Comment by xmonader** [comment]
fixed in 7c8e67067feef0f35b9bb01af790394ed369ceca
