### ISSUE TITLE
raise Connection timed out in stderr not stdout 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtecharchive/zosctl#55]
> need to raise ```Connection timed out``` error for ```zos ping``` instead of raising it for the output of command. ( it raise correct exit code but for wrong standard output ( raise it for stdout not stderr ))

- node_reach = subprocess.run(["zos ping"], shell=True, stdout = subprocess.PIPE, stderr = subprocess.PIPE)
- node_reach.stderr
``` b'' ```
-  node_reach.stdout
``` b"Connection timed out\nERROR [-]can't reach zos\n"```

**Comment by xmonader** [comment]
Nim bug: https://github.com/nim-lang/Nim/issues/9547

**Comment by xmonader** [comment]
PR merged in nim upstream and available on devel branch
https://github.com/nim-lang/Nim/commit/df68c2da49f99cea5824623d2512b5be27a9a116
