### ISSUE TITLE
can setdefault to unconfigured instance 

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#56]
you can use any arbitary name to setdefault 

`./zos setdefault UNCONFIGURED_INSTANCE`

**Comment by xmonader** [comment]
Fixed here https://github.com/threefoldtech/zos/commit/98fcb49efe474690f2c2f137e238be717e21a70c

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version :
119f136b55ffa16a67688a933f4ec5cd2378b17e

# verification steps:
- zos  setdefault domdom

```
ERROR instance domdom isn't configured to be used as default
```
