### ISSUE TITLE
ssh flist should be ubuntu 18.04

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#59]
until we have a clean solution for dropbear / openssh layer against ubuntu 18.04 also will solve conflicts in libraries

**Comment by xmonader** [comment]
closed via https://github.com/threefoldtech/zos/commit/48e8c21ddf0401bd2276633f3554dcaaa7498808

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
d67948b2605a94c341e1cd54147143017500786b

# Verification steps:
> create a redis container , and try to connect to it and check the OS. 

-  ./zos container new --name=test_con_1 --root=https://hub.grid.tf/thabet/redis.flist

```INFO preparing container
INFO sending instructions to host
INFO container 2 is created.
INFO opening port 19002
INFO creating portforward from 19002 to 22
INFO waiting for private network connectivity
Address string
container private address: 192.168.56.102
```

- ./zos container shell

- lsb_release -d
```
Description:	Ubuntu 18.04 LTS
```

> trying to create a
