### ISSUE TITLE
merge user flists with minimal dropbear/busybox flists to enable ssh insteald of full blown ubuntu

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#6]
ssh depends on ubuntu flists by default, investigate the possibility of  merged flist with dropbear/busybox to whatever flist the user is launching the container with instead

**Comment by zaibon** [comment]
dropbear is known to be bugy. So sshd is fine. But currently 0-os doesn't allow you to update the root flist of a container at runtime, so merge flist only when needed is not going to work. But I had another idea, we could add a primitives to 0-os itself, that allows to copy the sshd binaries and libs into the filesystem of the container. So we could, at runtime, install ssh and allow remote access inside the container on demand.

@muhamadazmy what do you think about that ?

**Comment by muhamadazmy** [comment]
After thinking about it, we really have many ways to achieve this, which includes:
- Merge flist on hub
- ZOS copy busybox and sshd binaries to container root as part of initialisation step (very specific to our use case)
- Another idea and I think it's very clean and would do better is to do runtime merging of flists. So 0-fs can take care of layring flists in runtime. This will require some change in 0-fs but shouldn't take.

**Comment by zaibon** [comment]
> Merge flist on hub

Not a solution, we don't want to have to each flist double

> ZOS copy busybox and sshd binaries to container root as part of initialisation step (very specific to our use case)

This should not be at initialization, but only when asked by the use during the runtime of the container, is this still a possibility ?

> Another idea and I think it's very clean and would do better is to do runtime merging of flists. So 0-fs can take care of layring flists in runtime. This will require some change in 0-fs but shouldn't take.

That sounds like the best option indeed, but merging flist is not that trivial. Do you think that something we could implement in a couple of days ?

**Comment by muhamadazmy** [comment]
> This should not be at initialization, but only when asked by the use during the runtime of the container, is this still a possibility ?
it is possible of course, but since the client know the container root, I don't think you need any changes in zos, since u can copy whatever files (even upload) to the container. I hate introducing such a primitive to zos because it only serves one use case and will require zos to pack the needed binary locally. Hence I prefer the second solution

> 
> > Another idea and I think it's very clean and would do better is to do runtime merging of flists. So 0-fs can take care of layring flists in runtime. This will require some change in 0-fs but shouldn't take.
> 
> That sounds like the best option indeed, but merging flist is not that trivial. Do you think that something we could implement in a couple of days ?

I think it will take couple of hours to implement. So I can finish that today if i started on it now.

**Comment by zaibon** [comment]
nice, let's create the issue on [0-fs](https://github.com/threefoldtech/0-fs) then

**Comment by zaibon** [comment]
@xmonader you can then already prepare an flist that contains the sshd and all it's libs

**Comment by muhamadazmy** [comment]
@xmonader make sure it includes a shell as well plus busybox

**Comment by xmonader** [comment]
Still struggling with https://hub.grid.tf/thabet/busyssh.flist.md and still using full ubuntu on any flist

Problems mainly are related to "separation user, directory and not recognizing user root"


```bash
~> ./zos container new --name=acont --root="https://hub.grid.tf/thabet/redis.flist"
INFO dispatch creating acont on machine https://hub.grid.tf/thabet/redis.flist false
INFO new container: corex.create {"name":"acont","hostname":"acont","root":"https://hub.grid.tf/thabet/redis.flist","privileged":false,"nics":[{"type":"default"},{"type":"zerotier","id":"9bee8941b5717835"}],"config":{"/root/.ssh/authorized_keys":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeq1MFCQOv3OCLO1HxdQl8V0CxAwt5AzdsNOL91wmHiG9ocgnq2yipv7qz+uCS0AdyOSzB9umyLcOZl2apnuyzSOd+2k6Cj9ipkgVx4nx4q5W1xt4MWIwKPfbfBA9gDMVpaGYpT6ZEv2ykFPnjG0obXzIjAaOsRthawuEF8bPZku1yi83SDtpU7I0pLOl3oifuwPpXTAVkK6GabSfbCJQWBDSYXXM20eRcAhIMmt79zo78FNItHmWpfPxPTWlYW02f7vVxTN/LUeRFoaNXXY+cuPxmcmXp912kW0vhK9IvWXqGAEuSycUOwync/yj+8f7dRU7upFGqd6bXUh67iMl7 ahmed@ahmedheaven\n"}}
231





10.244.113.16
                                                                                    ✔  ahmed@ahmedheaven
~> ./zos container shell                                                                    ✔  ahmed@ahmedheaven
INFO layering sshflist on container
INFO layered sshflist on container


 * Starting OpenBSD Secure Shell server sshd
   ...done.

Warning: Permanently added '10.244.113.16' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.14.36-Zero-OS x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

root@acont:~#
```

This is the workaround we will be using until we figure out how to run the ssh from the flist
