### ISSUE TITLE
Selection of Zero-OS in zos command line

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/zosctl#62]
When using the zos command line there is no option to have some of the container commenad operate on different Zero-OS machines.  The only way I have been able to switch from machine to machine is to init all the machines and then change the default Zero-OS machine.

For example if I want to delete container #3 on Zero-OS machine #1 and container #2 on Zero-OS #101

See:
  zos init --name=<zosmachine> [--disksize=<disksize>] [--memory=<memorysize>] [--redisport=<redisport>] [--reset]
  zos configure --name=<zosmachine> [--address=<address>] [--port=<port>] [--setdefault]
  zos remove --name=<zosmachine>
  zos ping
  zos showconfig
  zos setdefault <zosmachine>
  zos cmd <zoscommand> [--jsonargs=<args>]
  zos exec <command>
  zos container new --name=<name> --root=<rootflist> [--hostname=<hostname>] [--ports=<ports>] [--env=<envvars>] [--sshkey=<sshkey>] [--privileged] [--ssh]
  zos container inspect
  zos container info [--json]
  zos container list [--json]
  zos container <id> inspect
  zos container <id> info
  zos container <id> delete
  zos container <id> zerotierinfo
  zos container <id> zerotierlist
  zos container <id> zosexec <command>
  zos container <id> sshenable
  zos container <id> sshinfo
  zos container <id> shell
  zos container <id> exec <command>
  zos container sshenable
  zos container sshinfo
  zos container shell
  zos container exec <command>
  zos container <id> upload <file> <dest>
  zos container <id> download <file> <dest>
  zos container upload <file> <dest>
  zos container download <file> <dest>
  zos help <cmdname>

**Comment by xmonader** [comment]
I kinda agree, not on all options though, maybe on create and delete only.

Anyways, the state of the whole project is now undetermined. (i will put it on roadmap)
