### ISSUE TITLE
zos  on mac gives error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#64]
# Installation information

- operating system: mac

# Detailed description
when executing `zos ping`  you get `error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`

## Expected behavior
ping or connection refused
## Actual behavior
``` zos ping
error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
ERROR [-]can't reach zos
```

## Suggested solutions

upgrade openssl to 1.1 `brew install openssl@1.1`

check code here https://github.com/nim-lang/Nim/blob/master/lib/wrappers/openssl.nim#L62

## more info

```bash
iMac-Pro:zos wimtimmer$ brew install openssl@1.1
Warning: openssl@1.1 1.1.1 is already installed and up-to-date
To reinstall 1.1.1, run brew reinstall openssl@1.1
iMac-Pro:zos wimtimmer$ zos ping
error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
ERROR [-]can't reach zos
iMac-Pro:zos wimtimmer$ openssl version
LibreSSL 2.6.4
iMac-Pro:zos wimtimmer$
```
using openssl10 flag didn't work too

```bash
iMac-Pro:zos wimtimmer$ sudo nimble build -d:openssl10 --threads:on
  Verifying dependencies for zos@0.1.0
      Info: Dependency on docopt@#head already satisfied
  Verifying dependencies for docopt@#head
      Info: Dependency on redisclient@#head already satisfied
  Verifying dependencies for redisclient@#head
      Info: Dependency on redisparser@>= 0.1.0 already satisfied
  Verifying dependencies for redisparser@0.1.0
      Info: Dependency on uuids@any version already satisfied
  Verifying dependencies for uuids@0.1.10
      Info: Dependency on isaac@>= 0.1.3 already satisfied
  Verifying dependencies for isaac@0.1.3
   Building zos/zos using c backend
iMac-Pro:zos wimtimmer$ zos ping
error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
ERROR [-]can't reach zos
```

## update
This old binary (built from master) on mac worked fine 
![image](https://user-images.githubusercontent.com/64129/48091334-0ff80000-e212-11e8-84d5-65267aa6a8d9.png)

which means we either broke it by the redis timeouts in ssl connections  (which is the most likely) or something else to trace
![image](https://user-images.githubusercontent.com/64129/48091434-577e8c00-e212-11e8-9d1f-2c0f8db4c041.png)

- compiling with sudo seems to work?

**Comment by xmonader** [comment]
Successfully upgraded using 

1- brew install openssl@1.1
2- executing the following
```
nim c -d:ssl  --dynlibOverride:ssl --dynlibOverride:crypto --threads:on --passC:'-I/usr/local/opt/openssl\@1.1/include/' --passL:'-lssl -lcrypto -lpcre' --passL:'-L/usr/local/opt/openssl\@1.1/lib/' src/zos.nim

```
The prev command might require a `sudo`

![image](https://user-images.githubusercontent.com/64129/48136834-56e50480-e2a9-11e8-99d0-2f0f780306f6.png)

![image](https://user-images.githubusercontent.com/64129/48136838-5a788b80-e2a9-11e8-9dc8-39ab5c9ef755.png)

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
cdcdcf6cb860a9287ba9397df7f51406c4ba2c2a

# Verification Steps:
- sudo bash build.sh 
- zosMac ping

```
"PONG Version: development @Revision: 06091505e87a2b6b44e0ee49541acf630a175678"
```
