### ISSUE TITLE
zos remove --name is misleading

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#65]
remove option doesn't remove the instance config it just removes the vbox machine

**Comment by xmonader** [comment]
fixed 7128bd932c23537a4901dbe7be2b275b48e442ea

**Comment by Dina-Abd-Elrahman** [comment]
# verification steps :

- create virtualbox instance and and try to check the info if it is removed from config file or not,  and check the vm disk if removed from virtualbox or not
