### ISSUE TITLE
Simplify output

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/zosctl#7]
I've seen the output of the zos command are most of the time the full dump of what 0-OS returns. In most cases that's too much information for the user. We should only print the minimal information to keep a clean and clear screen. 
If the user wants full detail we could had an `inspect` command or something like docker does.

Docker is a good example of the right balance, when you list your containers, it only print the minimal useful information about them : ID, Image, created data, status, ports forwards, name.
In our case not everything is the same as docker but we can pick the useful information too and print it in a nice way.

**Comment by xmonader** [comment]
fixed default usage will show table for container info and lots of improvements on the messages shown to user thanks to @maxux 

![selection_041](https://user-images.githubusercontent.com/64129/47355937-04112780-d6c3-11e8-81f6-f8549dd0203e.jpg)
and --json parameter will show output as json

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
c88753bb25cad433b416929593eee99598a3d7d2

# Verification steps:
- zos container info

![zos](https://user-images.githubusercontent.com/21218053/47369181-6d089780-d6e3-11e8-9edb-6f8936642bf3.png)
