### ISSUE TITLE
allow using zos without forcing zerotier for virtualbox instances

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#70]
allow using zos without forcing zerotier for virtualbox instances so you don't have to use zerotier to use zos

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
3ff5eab9afef6553bb3e9a82b489f094ea3a7356

# Verification scenario:
> stop zerotier service locally and check if i can create virtualbox instances using zos command or not 

- service zerotier-one stop
- ./zos init --name="test" --redisport=9999
