### ISSUE TITLE
New compile on Mabook is broken.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/zosctl#74]
Compile command fails.  

# Installation information

int: errorcodes [Processing]
Hint: namegenerator [Processing]
Hint: random [Processing]
zos.nim(309, 18) Warning: Number of spaces around '&' is not consistent [Spacing]
zos.nim(309, 40) Warning: Number of spaces around '+' is not consistent [Spacing]
zos.nim(309, 171) Warning: Number of spaces around '&' is not consistent [Spacing]
zos.nim(315, 258) Warning: Number of spaces around '+' is not consistent [Spacing]
zos.nim(883, 8) Hint: 'handleConfigured.handleContainerAuthorize()[declared in zos.nim(883, 7)]' is declared but not used [XDeclaredButNotUsed]
zos.nim(27, 6) Hint: 'zos.sshBinsCheck()[declared in zos.nim(27, 5)]' is declared but not used [XDeclaredButNotUsed]
zos.nim(386, 6) Hint: 'zos.containerHasIP(this: App, containerid: int)[declared in zos.nim(386, 5)]' is declared but not used [XDeclaredButNotUsed]
Error: cannot open '/Users/weynandkuijpers/.cache/nim/zos_d/stdlib_sharedlist.c'
Weynands-MacBook-Pro:zos weynandkuijpers$
- operating system:
- zos version `zos --version`:
- target zero-os version `zos ping`:

# Detailed description

## Actual behavior

# Steps to reproduce

# Stacktraces if any

# Possible solution(s)

**Comment by xmonader** [comment]
@weynandkuijpers  Did you execute with sudo?

**Comment by xmonader** [comment]
I'll close it for now please reopen if it's still an issue
