### ISSUE TITLE
naming machine app may break zos

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#76]
either forbid using `app` as a name or prepend `instance-` to all machine names in the config file.

**Comment by xmonader** [comment]
fixed here 60ee0b5ca5666d03a454f866974d36563b13bf82 (don't allow app as a machine name)

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS version:
d67948b2605a94c341e1cd54147143017500786b

# Verification steps:
> trying to create a machine with name app. 

- ./zos init --name=app

`
ERROR app is invalid machine name
`
