### ISSUE TITLE
out of range error for zero-os machine with 0 containers running 

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#77]
when doing container list on empty machine (has no containers) you will get out of range error

**Comment by xmonader** [comment]
fixed here d67948b2605a94c341e1cd54147143017500786b

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version:
d67948b2605a94c341e1cd54147143017500786b

# Verification steps:
> we delete all containers from ZOS node and check the output. 

- ./zos container list

`INFO machine doesn't have any active containers.`
