### ISSUE TITLE
containers on remote machine execution shouldn't depend only on zerotier

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/zosctl#80]
As zerotier is getting more and more unreliable, let's use the reachable zero-os machine and portforwards in zero-os as the main ip solution for the container. 

> Container IP is the same as the machine IP

**Comment by Dina-Abd-Elrahman** [comment]
# ZOS Version :
c8e6ded3560ef4175721b3d361bfae4153444906

# Verification Steps :
> connect for a node in kds farm, and try to create a container a new created containers should take the same ip of the node, and new port should be created on the node. 

- ./zos configure --name=test --address=10.102.133.88  --port=6379 --setdefault
- ./zos container new 
```
INFO preparing container
INFO sending instructions to host
INFO container 6 is created.
INFO opening port 1026
INFO creating portforward from 1026 to 22
INFO waiting for private network connectivity
container private address: 10.102.133.88
```
> we need to check if the new created port is opened on the zos node or not.
-  node = j.clients.zos.get('c7c8172af1f387a6', data={'host':'10.102.133.88'})
- node.client.nft.list()
```
['iifname "zt*" tcp dport 6379 accept', 'tcp dport 1026 accept']
```
