### ISSUE TITLE
failed to create a zos machine via virtualbox 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtecharchive/zosctl#84]
![image](https://user-images.githubusercontent.com/17981089/49575732-16ca7d80-f94c-11e8-8d0c-8754c44215f7.png)

╰─# vboxmanage --version
5.0.40_Ubuntur115130

**Comment by maxux** [comment]
What's your VirtualBox version ?

**Comment by 0xIslamTaha** [comment]
@maxux I updated the ticket 
 vboxmanage --version
5.0.40_Ubuntur115130

**Comment by maxux** [comment]
Please update to >= 5.2

**Comment by 0xIslamTaha** [comment]
I think we need to update the docs to clarify that

**Comment by xmonader** [comment]
even 5.1 version isn't supported anymore https://www.virtualbox.org/wiki/Download_Old_Builds_5_1

@0xIslamTaha I updated the troubleshooting and main readme 83f53e397fa626a8de3fdbfa5a426742fc1b9604
