### ISSUE TITLE
how do you connect a container to a specific zerotier network?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/zosctl#92]
# Installation information

- operating system: osx
- zos version `zos --version`: 0.1.0
- target zero-os version `zos ping`:

# Detailed description
Browsing through the documentation, I could not find how to connect a container to a specific zerotier network using the zos tool.
## Actual behavior

# Steps to reproduce

# Stacktraces if any

# Possible solution(s)

**Comment by xmonader** [comment]
By default zos adds a nic of type zerotier https://github.com/threefoldtech/zos/blob/75da342a28864ebfa96442847ee4e7d400f820d7/src/zos.nim#L198

the zerotierId is controlled using `GRID_ZEROTIER_ID` or `GRID_ZEROTIER_ID_TESTING` environment variables.

Maybe it's better to be added as an explicit command line argument to container new

**Comment by robvanmieghem** [comment]
agreed, it was nowhere mentioned in the documentation either

**Comment by robvanmieghem** [comment]
thanks for documenting, I created a non urgent follow up issue : #95
